version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    versioning-strategy: "auto"
    labels:
      - "dependencies"
      - "pnpm"
    commit-message:
      prefix: "chore"
      include: "scope"
